"""Frozen post-v2 Reading Order qualification tooling."""

EXPERIMENT_ID = "reading-order-post-v2-c1-c2-c3-b1-v1"
SPEC_SCHEMA_VERSION = "reading-order-post-v2-experiment-spec-v1"
DIAGNOSTIC_SCHEMA_VERSION = "reading-order-post-v2-diagnostic-v1"
EVIDENCE_SCHEMA_VERSION = "reading-order-post-v2-evidence-v1"
CORPUS_DESIGN_SCHEMA_VERSION = "reading-order-post-v2-corpus-design-v1"
CORPUS_MANIFEST_SCHEMA_VERSION = "reading-order-post-v2-corpus-manifest-v1"
INPUT_SCHEMA_VERSION = "reading-order-post-v2-input-v1"
ANNOTATION_SCHEMA_VERSION = "reading-order-post-v2-annotation-v1"
