"""create initial schema

Revision ID: b12467733e37
Revises:
Create Date: 2026-08-07 23:17:19.146847
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b12467733e37"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA mangasensei")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gemini_budget_buckets",
        sa.Column("budget_date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "reserved_amount", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.Column(
            "actual_amount", sa.Numeric(precision=14, scale=6), server_default="0", nullable=False
        ),
        sa.CheckConstraint(
            "reserved_amount >= 0 AND actual_amount >= 0",
            name=op.f("ck_gemini_budget_buckets_amounts_nonnegative"),
        ),
        sa.PrimaryKeyConstraint("budget_date", "currency", name=op.f("pk_gemini_budget_buckets")),
        schema="mangasensei",
    )
    op.create_table(
        "image_blobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="ready", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "media_type IN ('image/jpeg','image/png','image/webp')",
            name=op.f("ck_image_blobs_media_type"),
        ),
        sa.CheckConstraint("state IN ('ready','deleting')", name=op.f("ck_image_blobs_state")),
        sa.CheckConstraint(
            "byte_size > 0 AND byte_size <= 12582912", name=op.f("ck_image_blobs_byte_size_range")
        ),
        sa.CheckConstraint(
            "height > 0 AND height <= 10000", name=op.f("ck_image_blobs_height_range")
        ),
        sa.CheckConstraint("octet_length(sha256) = 32", name=op.f("ck_image_blobs_sha256_length")),
        sa.CheckConstraint("width * height <= 25000000", name=op.f("ck_image_blobs_pixel_limit")),
        sa.CheckConstraint("width > 0 AND width <= 10000", name=op.f("ck_image_blobs_width_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_blobs")),
        sa.UniqueConstraint("sha256", name=op.f("uq_image_blobs_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_image_blobs_storage_key")),
        schema="mangasensei",
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), server_default=sa.text("uuidv4()"), nullable=False),
        sa.Column("image_blob_id", sa.BigInteger(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("upload_key_id", sa.String(length=32), nullable=False),
        sa.Column("upload_idempotency_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("request_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP + INTERVAL '24 hours'"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expires_at = created_at + interval '24 hours'", name=op.f("ck_pages_retention_exact")
        ),
        sa.CheckConstraint(
            "octet_length(request_digest) = 32", name=op.f("ck_pages_request_digest_length")
        ),
        sa.CheckConstraint(
            "octet_length(upload_idempotency_digest) = 32",
            name=op.f("ck_pages_idempotency_digest_length"),
        ),
        sa.ForeignKeyConstraint(
            ["image_blob_id"],
            ["mangasensei.image_blobs.id"],
            name=op.f("fk_pages_image_blob_id_image_blobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("public_id", name=op.f("uq_pages_public_id")),
        sa.UniqueConstraint(
            "upload_key_id",
            "upload_idempotency_digest",
            name=op.f("uq_pages_upload_key_id_upload_idempotency_digest"),
        ),
        schema="mangasensei",
    )
    op.create_index(
        "ix_pages_expires_at_id", "pages", ["expires_at", "id"], unique=False, schema="mangasensei"
    )
    op.create_index(
        "ix_pages_image_blob_id", "pages", ["image_blob_id"], unique=False, schema="mangasensei"
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), server_default=sa.text("uuidv4()"), nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("job_kind", sa.String(length=32), server_default="page_analysis", nullable=False),
        sa.Column("idempotency_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("request_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), server_default="pending", nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=True),
        sa.Column("fencing_token", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pipeline_version", sa.String(length=64), server_default="0.1.0", nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((status IN ('claimed','processing_ocr','processing_linguistics','processing_gemini') AND worker_id IS NOT NULL AND lease_expires_at IS NOT NULL AND heartbeat_at IS NOT NULL) OR (status NOT IN ('claimed','processing_ocr','processing_linguistics','processing_gemini') AND worker_id IS NULL AND lease_expires_at IS NULL AND heartbeat_at IS NULL))",
            name=op.f("ck_jobs_lease_ownership"),
        ),
        sa.CheckConstraint(
            "((status IN ('completed','failed','expired') AND finished_at IS NOT NULL) OR (status NOT IN ('completed','failed','expired') AND finished_at IS NULL))",
            name=op.f("ck_jobs_terminal_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','claimed','processing_ocr','processing_linguistics','processing_gemini','completed','retryable_failure','failed','expired')",
            name=op.f("ck_jobs_status"),
        ),
        sa.CheckConstraint(
            "attempt_count >= 0 AND attempt_count <= max_attempts",
            name=op.f("ck_jobs_attempt_range"),
        ),
        sa.CheckConstraint("fencing_token >= 0", name=op.f("ck_jobs_fencing_nonnegative")),
        sa.CheckConstraint("max_attempts > 0", name=op.f("ck_jobs_max_attempts_positive")),
        sa.CheckConstraint(
            "octet_length(idempotency_digest) = 32", name=op.f("ck_jobs_idempotency_length")
        ),
        sa.CheckConstraint(
            "octet_length(request_digest) = 32", name=op.f("ck_jobs_request_digest_length")
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["mangasensei.pages.id"],
            name=op.f("fk_jobs_page_id_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint(
            "page_id",
            "job_kind",
            "idempotency_digest",
            name=op.f("uq_jobs_page_id_job_kind_idempotency_digest"),
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_jobs_public_id")),
        schema="mangasensei",
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        ["available_at", "id"],
        unique=False,
        schema="mangasensei",
        postgresql_where=sa.text("status IN ('pending','retryable_failure')"),
    )
    op.create_index(
        "ix_jobs_page_created",
        "jobs",
        ["page_id", "created_at", "id"],
        unique=False,
        schema="mangasensei",
    )
    op.create_index(
        "ix_jobs_recovery",
        "jobs",
        ["lease_expires_at", "id"],
        unique=False,
        schema="mangasensei",
        postgresql_where=sa.text(
            "status IN ('claimed','processing_ocr','processing_linguistics','processing_gemini')"
        ),
    )
    op.create_index(
        "uq_jobs_one_active_page",
        "jobs",
        ["page_id"],
        unique=True,
        schema="mangasensei",
        postgresql_where=sa.text(
            "status IN ('pending','claimed','processing_ocr','processing_linguistics','processing_gemini','retryable_failure')"
        ),
    )
    op.create_table(
        "page_capabilities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "scope IN ('read:page','read:image','reprocess:page')",
            name=op.f("ck_page_capabilities_scope"),
        ),
        sa.CheckConstraint(
            "octet_length(digest) = 32", name=op.f("ck_page_capabilities_digest_length")
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["mangasensei.pages.id"],
            name=op.f("fk_page_capabilities_page_id_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_page_capabilities")),
        sa.UniqueConstraint("key_id", "digest", name=op.f("uq_page_capabilities_key_id_digest")),
        schema="mangasensei",
    )
    op.create_index(
        "ix_page_capabilities_page_id_scope",
        "page_capabilities",
        ["page_id", "scope"],
        unique=False,
        schema="mangasensei",
    )
    op.create_table(
        "gemini_calls",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), server_default=sa.text("uuidv4()"), nullable=False),
        sa.Column("page_id", sa.BigInteger(), nullable=True),
        sa.Column("job_id", sa.BigInteger(), nullable=True),
        sa.Column("page_call_ordinal", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("request_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("provider_request_id", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=16), server_default="reserved", nullable=False),
        sa.Column("reserved_cost", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('reserved','sent','succeeded','failed','unknown')",
            name=op.f("ck_gemini_calls_state"),
        ),
        sa.CheckConstraint(
            "octet_length(request_digest) = 32", name=op.f("ck_gemini_calls_request_digest_length")
        ),
        sa.CheckConstraint(
            "page_call_ordinal BETWEEN 1 AND 3", name=op.f("ck_gemini_calls_call_ordinal")
        ),
        sa.CheckConstraint(
            "reserved_cost >= 0", name=op.f("ck_gemini_calls_reserved_cost_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["mangasensei.jobs.id"],
            name=op.f("fk_gemini_calls_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["page_id"],
            ["mangasensei.pages.id"],
            name=op.f("fk_gemini_calls_page_id_pages"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gemini_calls")),
        sa.UniqueConstraint(
            "page_id", "page_call_ordinal", name=op.f("uq_gemini_calls_page_id_page_call_ordinal")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_gemini_calls_public_id")),
        schema="mangasensei",
    )
    op.create_index(
        "uq_gemini_calls_provider_request_id",
        "gemini_calls",
        ["provider_request_id"],
        unique=True,
        schema="mangasensei",
        postgresql_where=sa.text("provider_request_id IS NOT NULL"),
    )
    op.create_table(
        "job_attempts",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("worker_id", sa.String(length=128), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.CheckConstraint("attempt_no > 0", name=op.f("ck_job_attempts_attempt_positive")),
        sa.CheckConstraint("fencing_token > 0", name=op.f("ck_job_attempts_fencing_positive")),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["mangasensei.jobs.id"],
            name=op.f("fk_job_attempts_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "attempt_no", name=op.f("pk_job_attempts")),
        sa.UniqueConstraint(
            "job_id", "fencing_token", name=op.f("uq_job_attempts_job_id_fencing_token")
        ),
        schema="mangasensei",
    )
    op.create_table(
        "ocr_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("detector", sa.String(length=64), nullable=False),
        sa.Column("recognizer", sa.String(length=64), nullable=False),
        sa.Column("model_manifest_version", sa.String(length=64), nullable=False),
        sa.Column("config_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("upstream_repository", sa.Text(), nullable=False),
        sa.Column("upstream_commit", sa.String(length=128), nullable=False),
        sa.Column("input_sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(input_sha256) = 32", name=op.f("ck_ocr_runs_input_sha256_length")
        ),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_ocr_runs_dimensions_positive")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["mangasensei.jobs.id"],
            name=op.f("fk_ocr_runs_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_runs")),
        sa.UniqueConstraint(
            "job_id", "fencing_token", name=op.f("uq_ocr_runs_job_id_fencing_token")
        ),
        schema="mangasensei",
    )
    op.create_table(
        "gemini_cost_ledger",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("gemini_call_id", sa.BigInteger(), nullable=False),
        sa.Column("observation_key", sa.String(length=128), nullable=False),
        sa.Column("pricing_version", sa.String(length=64), nullable=False),
        sa.Column("usage_category", sa.String(length=32), nullable=False),
        sa.Column("token_quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit_rate", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="USD", nullable=False),
        sa.Column("amount", sa.Numeric(precision=14, scale=6), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "token_quantity >= 0", name=op.f("ck_gemini_cost_ledger_token_quantity_nonnegative")
        ),
        sa.CheckConstraint(
            "unit_rate >= 0", name=op.f("ck_gemini_cost_ledger_unit_rate_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["gemini_call_id"],
            ["mangasensei.gemini_calls.id"],
            name=op.f("fk_gemini_cost_ledger_gemini_call_id_gemini_calls"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gemini_cost_ledger")),
        sa.UniqueConstraint(
            "gemini_call_id",
            "observation_key",
            name=op.f("uq_gemini_cost_ledger_gemini_call_id_observation_key"),
        ),
        schema="mangasensei",
    )
    op.create_table(
        "linguistic_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("ocr_run_id", sa.BigInteger(), nullable=False),
        sa.Column("fencing_token", sa.BigInteger(), nullable=False),
        sa.Column("tokenizer_name", sa.String(length=64), nullable=False),
        sa.Column("tokenizer_version", sa.String(length=64), nullable=False),
        sa.Column("config_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("dictionary_name", sa.String(length=64), nullable=False),
        sa.Column("dictionary_version", sa.String(length=64), nullable=False),
        sa.Column("dictionary_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column("input_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(config_digest) = 32", name=op.f("ck_linguistic_runs_config_digest_length")
        ),
        sa.CheckConstraint(
            "octet_length(dictionary_digest) = 32",
            name=op.f("ck_linguistic_runs_dictionary_digest_length"),
        ),
        sa.CheckConstraint(
            "octet_length(input_digest) = 32", name=op.f("ck_linguistic_runs_input_digest_length")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["mangasensei.jobs.id"],
            name=op.f("fk_linguistic_runs_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["ocr_run_id"],
            ["mangasensei.ocr_runs.id"],
            name=op.f("fk_linguistic_runs_ocr_run_id_ocr_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_linguistic_runs")),
        sa.UniqueConstraint(
            "job_id", "fencing_token", name=op.f("uq_linguistic_runs_job_id_fencing_token")
        ),
        schema="mangasensei",
    )
    op.create_table(
        "ocr_regions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_id", sa.UUID(), server_default=sa.text("uuidv4()"), nullable=False),
        sa.Column("ocr_run_id", sa.BigInteger(), nullable=False),
        sa.Column("region_ordinal", sa.Integer(), nullable=False),
        sa.Column("reading_order", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("normalized_x", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("normalized_y", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("normalized_width", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("normalized_height", sa.Numeric(precision=12, scale=10), nullable=False),
        sa.Column("angle", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=8, scale=7), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=True),
        sa.CheckConstraint("angle >= -180 AND angle <= 180", name=op.f("ck_ocr_regions_angle")),
        sa.CheckConstraint(
            "char_length(raw_text) BETWEEN 1 AND 10000", name=op.f("ck_ocr_regions_raw_text_length")
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_ocr_regions_confidence")
        ),
        sa.CheckConstraint(
            "normalized_height > 0 AND normalized_height <= 1",
            name=op.f("ck_ocr_regions_normalized_height"),
        ),
        sa.CheckConstraint(
            "normalized_width > 0 AND normalized_width <= 1",
            name=op.f("ck_ocr_regions_normalized_width"),
        ),
        sa.CheckConstraint(
            "normalized_x >= 0 AND normalized_x <= 1", name=op.f("ck_ocr_regions_normalized_x")
        ),
        sa.CheckConstraint(
            "normalized_y >= 0 AND normalized_y <= 1", name=op.f("ck_ocr_regions_normalized_y")
        ),
        sa.CheckConstraint(
            "x >= 0 AND y >= 0 AND width > 0 AND height > 0",
            name=op.f("ck_ocr_regions_bbox_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["ocr_run_id"],
            ["mangasensei.ocr_runs.id"],
            name=op.f("fk_ocr_regions_ocr_run_id_ocr_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ocr_regions")),
        sa.UniqueConstraint(
            "ocr_run_id", "reading_order", name=op.f("uq_ocr_regions_ocr_run_id_reading_order")
        ),
        sa.UniqueConstraint(
            "ocr_run_id", "region_ordinal", name=op.f("uq_ocr_regions_ocr_run_id_region_ordinal")
        ),
        sa.UniqueConstraint("public_id", name=op.f("uq_ocr_regions_public_id")),
        schema="mangasensei",
    )
    op.create_table(
        "gemini_analyses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("linguistic_run_id", sa.BigInteger(), nullable=False),
        sa.Column("gemini_call_id", sa.BigInteger(), nullable=False),
        sa.Column("response_digest", sa.LargeBinary(length=32), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(response_digest) = 32",
            name=op.f("ck_gemini_analyses_response_digest_length"),
        ),
        sa.ForeignKeyConstraint(
            ["gemini_call_id"],
            ["mangasensei.gemini_calls.id"],
            name=op.f("fk_gemini_analyses_gemini_call_id_gemini_calls"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["mangasensei.jobs.id"],
            name=op.f("fk_gemini_analyses_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["linguistic_run_id"],
            ["mangasensei.linguistic_runs.id"],
            name=op.f("fk_gemini_analyses_linguistic_run_id_linguistic_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gemini_analyses")),
        sa.UniqueConstraint("gemini_call_id", name=op.f("uq_gemini_analyses_gemini_call_id")),
        sa.UniqueConstraint("job_id", name=op.f("uq_gemini_analyses_job_id")),
        schema="mangasensei",
    )
    op.create_table(
        "linguistic_tokens",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("linguistic_run_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("token_ordinal", sa.Integer(), nullable=False),
        sa.Column("stable_key", sa.LargeBinary(length=32), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("surface", sa.Text(), nullable=False),
        sa.Column("lemma", sa.Text(), nullable=False),
        sa.Column("reading", sa.Text(), nullable=False),
        sa.Column("part_of_speech", sa.Text(), nullable=False),
        sa.Column("dictionary_entry_id", sa.String(length=128), nullable=True),
        sa.Column("dictionary_source", sa.String(length=64), nullable=True),
        sa.Column("jlpt_level", sa.String(length=2), nullable=True),
        sa.Column("jlpt_official", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "jlpt_level IS NULL OR jlpt_level IN ('N1','N2','N3','N4','N5')",
            name=op.f("ck_linguistic_tokens_jlpt"),
        ),
        sa.CheckConstraint(
            "octet_length(stable_key) = 32", name=op.f("ck_linguistic_tokens_stable_key_length")
        ),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset",
            name=op.f("ck_linguistic_tokens_offset_range"),
        ),
        sa.ForeignKeyConstraint(
            ["linguistic_run_id"],
            ["mangasensei.linguistic_runs.id"],
            name=op.f("fk_linguistic_tokens_linguistic_run_id_linguistic_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["mangasensei.ocr_regions.id"],
            name=op.f("fk_linguistic_tokens_region_id_ocr_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_linguistic_tokens")),
        sa.UniqueConstraint(
            "region_id", "token_ordinal", name=op.f("uq_linguistic_tokens_region_id_token_ordinal")
        ),
        sa.UniqueConstraint("stable_key", name=op.f("uq_linguistic_tokens_stable_key")),
        schema="mangasensei",
    )
    op.create_table(
        "ocr_region_vertices",
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("vertex_ordinal", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "x >= 0 AND y >= 0", name=op.f("ck_ocr_region_vertices_coordinates_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["mangasensei.ocr_regions.id"],
            name=op.f("fk_ocr_region_vertices_region_id_ocr_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("region_id", "vertex_ordinal", name=op.f("pk_ocr_region_vertices")),
        schema="mangasensei",
    )
    op.create_table(
        "gemini_region_analyses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.BigInteger(), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["mangasensei.gemini_analyses.id"],
            name=op.f("fk_gemini_region_analyses_analysis_id_gemini_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["mangasensei.ocr_regions.id"],
            name=op.f("fk_gemini_region_analyses_region_id_ocr_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gemini_region_analyses")),
        sa.UniqueConstraint(
            "analysis_id", "region_id", name=op.f("uq_gemini_region_analyses_analysis_id_region_id")
        ),
        schema="mangasensei",
    )
    op.create_table(
        "linguistic_meanings",
        sa.Column("token_id", sa.BigInteger(), nullable=False),
        sa.Column("meaning_ordinal", sa.Integer(), nullable=False),
        sa.Column("meaning", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["mangasensei.linguistic_tokens.id"],
            name=op.f("fk_linguistic_meanings_token_id_linguistic_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("token_id", "meaning_ordinal", name=op.f("pk_linguistic_meanings")),
        schema="mangasensei",
    )
    op.create_table(
        "gemini_grammar_points",
        sa.Column("region_analysis_id", sa.BigInteger(), nullable=False),
        sa.Column("grammar_ordinal", sa.Integer(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_analysis_id"],
            ["mangasensei.gemini_region_analyses.id"],
            name=op.f("fk_gemini_grammar_points_region_analysis_id_gemini_region_analyses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "region_analysis_id", "grammar_ordinal", name=op.f("pk_gemini_grammar_points")
        ),
        schema="mangasensei",
    )
    op.create_table(
        "gemini_vocabulary_links",
        sa.Column("region_analysis_id", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_analysis_id"],
            ["mangasensei.gemini_region_analyses.id"],
            name=op.f("fk_gemini_vocabulary_links_region_analysis_id_gemini_region_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["mangasensei.linguistic_tokens.id"],
            name=op.f("fk_gemini_vocabulary_links_token_id_linguistic_tokens"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "region_analysis_id", "token_id", name=op.f("pk_gemini_vocabulary_links")
        ),
        schema="mangasensei",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gemini_vocabulary_links", schema="mangasensei")
    op.drop_table("gemini_grammar_points", schema="mangasensei")
    op.drop_table("linguistic_meanings", schema="mangasensei")
    op.drop_table("gemini_region_analyses", schema="mangasensei")
    op.drop_table("ocr_region_vertices", schema="mangasensei")
    op.drop_table("linguistic_tokens", schema="mangasensei")
    op.drop_table("gemini_analyses", schema="mangasensei")
    op.drop_table("ocr_regions", schema="mangasensei")
    op.drop_table("linguistic_runs", schema="mangasensei")
    op.drop_table("gemini_cost_ledger", schema="mangasensei")
    op.drop_table("ocr_runs", schema="mangasensei")
    op.drop_table("job_attempts", schema="mangasensei")
    op.drop_index(
        "uq_gemini_calls_provider_request_id",
        table_name="gemini_calls",
        schema="mangasensei",
        postgresql_where=sa.text("provider_request_id IS NOT NULL"),
    )
    op.drop_table("gemini_calls", schema="mangasensei")
    op.drop_index(
        "ix_page_capabilities_page_id_scope", table_name="page_capabilities", schema="mangasensei"
    )
    op.drop_table("page_capabilities", schema="mangasensei")
    op.drop_index(
        "uq_jobs_one_active_page",
        table_name="jobs",
        schema="mangasensei",
        postgresql_where=sa.text(
            "status IN ('pending','claimed','processing_ocr','processing_linguistics','processing_gemini','retryable_failure')"
        ),
    )
    op.drop_index(
        "ix_jobs_recovery",
        table_name="jobs",
        schema="mangasensei",
        postgresql_where=sa.text(
            "status IN ('claimed','processing_ocr','processing_linguistics','processing_gemini')"
        ),
    )
    op.drop_index("ix_jobs_page_created", table_name="jobs", schema="mangasensei")
    op.drop_index(
        "ix_jobs_claim",
        table_name="jobs",
        schema="mangasensei",
        postgresql_where=sa.text("status IN ('pending','retryable_failure')"),
    )
    op.drop_table("jobs", schema="mangasensei")
    op.drop_index("ix_pages_image_blob_id", table_name="pages", schema="mangasensei")
    op.drop_index("ix_pages_expires_at_id", table_name="pages", schema="mangasensei")
    op.drop_table("pages", schema="mangasensei")
    op.drop_table("image_blobs", schema="mangasensei")
    op.drop_table("gemini_budget_buckets", schema="mangasensei")
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA mangasensei")
